<img src = "bgsedsc_0.jpg">

## Extra challenges for Python (+Numpy and Pandas)

This is a short list of short challenges to verify your knowledge

### Lists

In [17]:
# Challenge 1: Create a list variable with a sequence of number from 1 to 10.
mylist=[1,2,3,4,5,6,7,8,9,10]
#or 
#mylist=list(range(1, 11))
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
# Challenge 2: From previous one,  set the 2nd and 6th elements to 'no value'
mylist[1]= mylist[5]=None

mylist

[1, None, 3, 4, 5, None, 7, 8, 9, 10]

In [19]:
# Challenge 3: From previous one,  print last 3 elements of the list
mylist[-3:]

[8, 9, 10]

In [29]:
# Challenge 4: From previous, sum all the elements that are different than None
# Hint: do it first with a for loop
# then as alternative, try the same with sum() of a list compehension that discards nulls

mysum=0
for i in mylist:
    if i is not None:
        mysum+=i
mysum

# or
#sum([i for i in mylist if i is not None])


47

## Tuples

In [3]:
# Challenge 1: Create a list of 6 tuples, each tuple would be a pair of name and an age (to your choice, but one has to be 'bob')
mytuple=[('bob',25),('bertha',32),('robert', 53),('dad',48),('angela',23),('liz',43)]
mytuple

[('bob', 25),
 ('bertha', 32),
 ('robert', 53),
 ('dad', 48),
 ('angela', 23),
 ('liz', 43)]

In [42]:
# Challenge 2: Print bob's age
mytuple[0][1] #knowing position

# or
#[age for name,age in mytuple if name=='bob']

[25]

In [47]:
# Challenge 3: Extract names of people whose age is under certain value
Limit=40
output=[]
for name,age in mytuple:
    if age<40:
        output+= [name]  
        # or output.append(name)
output

#or [name for name,age in mytuple if age<40]

['bob', 'bertha', 'angela']

## Dictionaries

In [12]:
# Challenge 1: Create a list of dictionaries using same info that we had in the list of tuple of challenge #1 in tuples
mydict=[{'name':'bob','age':25},{'name':'bertha','age':32},{'name':'robert','age': 53},
        {'name':'dad','age':48},{'name':'angela','age':23},{'name':'liz','age':43}]
mydict

[{'name': 'bob', 'age': 25},
 {'name': 'bertha', 'age': 32},
 {'name': 'robert', 'age': 53},
 {'name': 'dad', 'age': 48},
 {'name': 'angela', 'age': 23},
 {'name': 'liz', 'age': 43}]

In [13]:
# Challenge 2: Print bob's age
mydict[0]['age']

# if we don't know position
age=None
for person in mydict:
    if person['name']=='bob':
        age=person['age']
age

# or
#[person['age'] for person in mydict if person['name']=='bob']

25

In [14]:
# Challenge 3: Extract names of people whose age is under certain value
# Do it first using for a loop, then a list comprehension
Limit=40
out=[]
for person in mydict:
    if person['age']<Limit:
        out += [person['name']]
        #or out.append(person['name'])
out

#or [person['name'] for person in mydict if person['age']<Limit]

['bob', 'bertha', 'angela']

In [15]:
# Challenge 4: Add a new key to our list of dictionaries, that is the ages of best friends of the related person
ages=[[34,23,26],[21,19,45],[43,56],[24,35,41],[21,23,22],[45,41]]
for i in range(0,len(mydict)):
    mydict[i].update( {"best_friends":ages[i]})

mydict

[{'name': 'bob', 'age': 25, 'best_friends': [34, 23, 26]},
 {'name': 'bertha', 'age': 32, 'best_friends': [21, 19, 45]},
 {'name': 'robert', 'age': 53, 'best_friends': [43, 56]},
 {'name': 'dad', 'age': 48, 'best_friends': [24, 35, 41]},
 {'name': 'angela', 'age': 23, 'best_friends': [21, 23, 22]},
 {'name': 'liz', 'age': 43, 'best_friends': [45, 41]}]

## Functions

In [5]:
# Challenge 1: Build a function that receives as input one tuple from our list of tuples (tuples section) , and returns the name and (his age + 10)
def check_age(onetuple):
    return onetuple[0],onetuple[1]+10

# Test it with this function
onetuple=('bob',23)#one of the valid names
check_age(onetuple)

('bob', 33)

In [10]:
# Challenge 2: Apply previous function to all tuples in our list of tuples
output=[]
for tuples in mytuple:
    output+=check_age(tuples)
print(output)

#or [check_age(onetuple) for onetuple in mytuple]

['bob', 35, 'bertha', 42, 'robert', 63, 'dad', 58, 'angela', 33, 'liz', 53]


[('bob', 35),
 ('bertha', 42),
 ('robert', 63),
 ('dad', 58),
 ('angela', 33),
 ('liz', 53)]

In [19]:
# Challenge 3: Build a function that receives as input one name the dictionary that we built in challenge #3 (section dictionaries) and yields a tuple of 'name' and maximum age of best friends
# Test it with some names of our list of dictionaries
def check_best(name, dict):
    max_best=None
    for dict in mydict:        
        if dict['name']==name:
            max_best=max(dict['best_friends'])
    return max_best

check_best('bob', dict)

34

In [21]:
# Challenge 4: Modify previus function, so that handles names that are not present
# i.e. when checking a new names, yield a message such as ('Robert is not in our list')
def check_best(name, dict):
    max_best=None
    for dict in mydict:        
        if dict['name']==name:
            max_best=max(dict['best_friends'])
    if max_best is None:
        max_best=name+ ' is not in our list'
    return max_best


# Test it with a new name
check_best('Joan', dict)

'Joan is not in our list'

In [24]:
# Challenge 5: Aply previous function to all names in our list of dictionaries
out=[]
for dict in mydict:
    myname= dict['name']
    mybest=check_best(myname,mydict)
    out.append(mybest)
out



[34, 45, 56, 41, 23, 45]

## Numpy arrays

In [69]:
# Challenge 1: Create two vectors (arrays) whose content is (2,5,7) and (3,5,7)
# don't forget to import numpy module
import numpy as np
array1=np.array([2,5,7])
array2=np.array([3,5,7])
array1

array([2, 5, 7])

In [70]:
# Challenge 2: Compute the dot product of the previous vectors
array1.dot(array2)

80

In [72]:
# Challenge 3: Concatenate both vectors (arrays) into one
array=np.concatenate([array1,array2])
array

array([2, 5, 7, 3, 5, 7])

In [73]:
# Challenge 3: Get previous vector and reshape to a matrix (2d array) of 2 rows and 3 columns
matrix=array.reshape(2,3)
matrix

array([[2, 5, 7],
       [3, 5, 7]])

In [76]:
# Challenge 4: Create a similar matrix with values (3,6,3,1,1,0) and sum with previous matrix
matrix2=np.array([[3,6,3],[1,1,0]])
matrixsum= matrix+matrix2
matrixsum

array([[ 5, 11, 10],
       [ 4,  6,  7]])

In [82]:
# Challenge 5: From previous step, instead of sum, concatenate bot matrices, so that you end up having a 4x3 matrix (2d array)
matrixconc=np.concatenate((matrix,matrix2))
matrixconc

array([[2, 5, 7],
       [3, 5, 7],
       [3, 6, 3],
       [1, 1, 0]])

In [80]:
# Challenge 6: Extract elments #2 and #3 of rows #1 and#4 of previous matrix
matrixconc[[0,3],[1,2]]

array([5, 0])

In [81]:
# Challenge 7: Extract average value by rows of our matrix, and also mean value by columns
matrixconc.mean(axis=1)
matrixconc.mean(axis=0)

array([2.25, 4.25, 4.25])

# Pandas series

In [52]:
# Challenge 1: From our list of tuples created in #1 (tuples section), create a pandas series that has as index the names, and as values the ages
import pandas as pd
myseries=pd.Series(data=[age for names,age in mytuple],
                 index=[names for names,age in mytuple])
myseries

bob       25
bertha    32
robert    53
dad       48
angela    23
liz       43
dtype: int64

In [54]:
# Challenge 2: Set as empty value the second element of the series 
myseries.iloc[1]=None
#myseries['bertha']=None
myseries

bob       25.0
bertha     NaN
robert    53.0
dad       48.0
angela    23.0
liz       43.0
dtype: float64

In [55]:
# Challenge 3: Change bob's age to 52
myseries['bob']=52

In [56]:
# Challenge 4: Save the list of names acting as index, then reset index of the series
mynames=list(myseries.index)
myseries=myseries.reset_index(drop=True)
myseries

0    52.0
1     NaN
2    53.0
3    48.0
4    23.0
5    43.0
dtype: float64

In [59]:
# Challenge 5: Sort the series, print it to spot the maximum, and print the maximum age first using .iloc, then using index

myseries=myseries.sort_values()

print(myseries)

print(myseries.iloc[4])
print(myseries.dropna().iloc[len(myseries.dropna().index)-1])
myseries[2]

4    23.0
5    43.0
3    48.0
0    52.0
2    53.0
1     NaN
dtype: float64
53.0
53.0


53.0

In [66]:
# Challenge 6: Build a mask and remove empty values
mask=myseries.isna()==False
myseries=myseries[mask]
myseries

4    23.0
5    43.0
3    48.0
0    52.0
2    53.0
dtype: float64

In [65]:
myseries

4    23.0
5    43.0
3    48.0
0    52.0
2    53.0
1     NaN
dtype: float64

In [79]:
myseries>20

4    True
5    True
3    True
0    True
2    True
dtype: bool

In [84]:
# Challenge 7: Report names of people between 18 and 30 years
mask=(myseries>=18) & (myseries<=30)
myseries[mask]

4    23.0
dtype: float64

In [92]:
# Challenge 8: Build a function that raises a number to a power of two, and apply it to our series using .map
def power(number):
    return number**2

myseries.map(power)

# alternative
# def power(number,p):
#     return number**p

# myseries.apply(power,args=(2,))
    

4     529.0
5    1849.0
3    2304.0
0    2704.0
2    2809.0
dtype: float64